/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Assistente;
import Classes.Dentista;
import Classes.Paciente;
import DBdados.Dados;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rails
 */
public class frmAssistente extends javax.swing.JInternalFrame {

    private Dados bd;
    private Dentista den;
    private Assistente ass;
    private int AssistenteAtual = 0;
    private boolean alterarAssistente = false;
    private Paciente pAuxuliar;
        
    public void atualizarDados(Dados bd, Dentista den, Paciente pAuxiliar, Assistente aAuxiliar){
        this.bd = bd;
        this.den = den;
        this.pAuxuliar = pAuxiliar;
        this.ass = aAuxiliar;
    }
    
   
    public frmAssistente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtrg = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelfixo = new javax.swing.JTextField();
        txttelcel = new javax.swing.JTextField();
        jdadatacontratacao = new com.toedter.calendar.JDateChooser();
        cmbcargo = new javax.swing.JComboBox<>();
        cmdsalvar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        cmdanterior = new javax.swing.JButton();
        cmdprimeiro = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdproximo = new javax.swing.JButton();
        cmdadicionar = new javax.swing.JButton();
        cmdalterar = new javax.swing.JButton();
        cmddeletar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdbuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtsalario = new javax.swing.JTextField();
        jdadatapagamento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Dentista");

        jLabel1.setText("Identificador:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereco:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Rg:");

        jLabel7.setText("Cpf:");

        jLabel8.setText("Cargo:");

        jLabel9.setText("Data de contratação:");

        jLabel10.setText("Email:");

        jLabel11.setText("TelFixo:");

        jLabel12.setText("TelCel:");

        jLabel13.setText("Senha:");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrgActionPerformed(evt);
            }
        });

        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });

        cmbcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar cargo", "Dentista", "Assistente", "Secretaria", "Fornecedor" }));

        cmdsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/script_save.png"))); // NOI18N
        cmdsalvar.setToolTipText("salvar");
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });

        cmdanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Proximo.png"))); // NOI18N
        cmdanterior.setToolTipText("anterior");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Primeiro.png"))); // NOI18N
        cmdprimeiro.setToolTipText("primeiro");
        cmdprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeiroActionPerformed(evt);
            }
        });

        cmdultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ultimo.png"))); // NOI18N
        cmdultimo.setToolTipText("ultimo");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Anterior.png"))); // NOI18N
        cmdproximo.setToolTipText("proximo");
        cmdproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdproximoActionPerformed(evt);
            }
        });

        cmdadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        cmdadicionar.setToolTipText("adicionar");
        cmdadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdadicionarActionPerformed(evt);
            }
        });

        cmdalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        cmdalterar.setToolTipText("editar");
        cmdalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdalterarActionPerformed(evt);
            }
        });

        cmddeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        cmddeletar.setToolTipText("excluir");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        cmdcancelar.setToolTipText("cancelar");
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        cmdbuscar.setToolTipText("pesquisar");
        cmdbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbuscarActionPerformed(evt);
            }
        });

        jLabel14.setText("Salário:");

        jLabel15.setText("Data do Pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcpf)
                            .addComponent(txtbairro)
                            .addComponent(txtcidade)
                            .addComponent(txtendereco)
                            .addComponent(txtnome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 174, Short.MAX_VALUE))
                            .addComponent(txtrg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cmbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdadatacontratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtsenha))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttelcel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelfixo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdadatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(cmdadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel9)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdadatacontratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelfixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdadicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdalterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmddeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmdsalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdcancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmdanterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdproximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdultimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel7)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdadatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed
       
        //validação dos campos digitados pelo usuário
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o id para realizar o cadastro");
            txtid.requestFocusInWindow();//posicionar o cursor na barra
            return;
        }
        
        if(cmbcargo.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o cargo para realizar o cadastro");
            cmbcargo.requestFocusInWindow();
            return;
        }
        
        if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o nome para realizar o cadastro");
            txtnome.requestFocusInWindow();
            return;
        }

        String senha = new String(txtsenha.getPassword());

        if(senha.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar a senha para realizar o cadastro");
            txtsenha.requestFocusInWindow();
            return;
        }
        
        if(txtendereco.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o endereco para realizar o cadastro");
            txtendereco.requestFocusInWindow();
            return;
        }
        
        if(txtcidade.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar a cidade para realizar o cadastro");
            txtcidade.requestFocusInWindow();
            return;
        }
        
        if(txtbairro.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o bairro para realizar o cadastro");
            txtbairro.requestFocusInWindow();
            return;
        }
        
        if(txtrg.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o rg para realizar o cadastro");
            txtrg.requestFocusInWindow();
            return;
        }
        
        if(txtcpf.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o cpf para realizar o cadastro");
            txtcpf.requestFocusInWindow();
            return;
        }
        
        if(jdadatacontratacao.getDate().equals(null)){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar a data de contratação para realizar o cadastro");
            jdadatacontratacao.requestFocusInWindow();
            return;
        }
        
        if(txtemail.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o email para realizar o cadastro");
            txtemail.requestFocusInWindow();
            return;
        }
        
        if(txttelfixo.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o telefone fixo para realizar o cadastro");
            txttelfixo.requestFocusInWindow();
            return;
        }
        
        if(txttelcel.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o telefone celular para realizar o cadastro");
            txttelcel.requestFocusInWindow();
            return;
        }

        //Salvando assistente no banco de dados

       
       Assistente a = new Assistente(Integer.parseInt(txtid.getText()),
                                 txtnome.getText(),
                                 txtendereco.getText(),
                                 txtcidade.getText(),
                                 txtbairro.getText(),
                                 txtrg.getText(),
                                 txtcpf.getText(),
                                 (String)cmbcargo.getSelectedItem(),
                                 jdadatacontratacao.getDate(),
                                 txtemail.getText(),
                                 Integer.parseInt(txttelfixo.getText()),
                                 Integer.parseInt(txttelcel.getText()),
                                 senha,
                                 Double.parseDouble(txtsalario.getText()),
                                 jdadatapagamento.getDate());
       
       
       
       
       boolean AssistenteExiste = den.pesquisar(Integer.parseInt(txtid.getText()), bd);
       
        if(AssistenteExiste && this.alterarAssistente){
           this.alterarAssistente = false;
           a.editar(AssistenteAtual, a, bd);
           JOptionPane.showMessageDialog(rootPane, "Assistente editado com sucesso");
           return;
       }
       
       if(AssistenteExiste){
           JOptionPane.showMessageDialog(rootPane, "Assistente já cadastratdo no sistema");
           return;
       } else {
          a.cadastrar(a, bd);
          JOptionPane.showMessageDialog(rootPane, "Assistente cadastratdo com sucesso");
          //return;
       }
       
      
       
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdbuscar.setEnabled(true);
        
        txtid.setEnabled(false);
        txtnome.setEnabled(false);
        txtendereco.setEnabled(false);
        txtcidade.setEnabled(false);
        txtbairro.setEnabled(false);
        txtrg.setEnabled(false);
        txtcpf.setEnabled(false);
        cmbcargo.setSelectedIndex(0);
        txtrg.setEnabled(false);
        jdadatacontratacao.setDate(null);
        txtemail.setEnabled(false);
        txttelfixo.setEnabled(false);
        txttelcel.setEnabled(false);
        jdadatapagamento.setEnabled(false);
        txtsalario.setEnabled(false);
        txtsenha.setEnabled(false);

    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void txtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrgActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void cmdadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdadicionarActionPerformed
        
        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdadicionar.setEnabled(false);
        cmdalterar.setEnabled(false);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(false);
        
        txtid.setEnabled(true);
        txtnome.setEnabled(true);
        txtendereco.setEnabled(true);
        txtcidade.setEnabled(true);
        txtbairro.setEnabled(true);
        txtrg.setEnabled(true);
        txtcpf.setEnabled(true);
        cmbcargo.setSelectedIndex(0);
        txtrg.setEnabled(true);
        jdadatacontratacao.setDate(null);
        txtemail.setEnabled(true);
        txttelfixo.setEnabled(true);
        txttelcel.setEnabled(true);
        jdadatapagamento.setEnabled(true);
        txtsalario.setEnabled(true);
        txtsenha.setEnabled(true);
        
        
        txtid.setText("");
        txtnome.setText("");
        jdadatacontratacao.setDate(null);
        txtcidade.setText("");
        txtemail.setText("");
        txtendereco.setText("");
        txtbairro.setText("");
        txtrg.setText("");
        txtcpf.setText("");
        cmbcargo.setSelectedIndex(0);
        txttelfixo.setText("");
        txttelcel.setText("");
        jdadatapagamento.setDate(null);
        txtsalario.setText("");
        txtsenha.setText("");
        
        //cmdnovo = true;
        txtid.requestFocusInWindow();
    }//GEN-LAST:event_cmdadicionarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(false);
        cmdbuscar.setEnabled(true);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void cmdprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeiroActionPerformed
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);

        if(bd.getAssistentes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        vizualizarAssistente(0);
        this.AssistenteAtual = 0;
        
    }//GEN-LAST:event_cmdprimeiroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        if(bd.getAssistentes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        vizualizarAssistente(bd.retornaIndiceUltimoCadastroAssistente());
        this.AssistenteAtual = bd.retornaIndiceUltimoCadastroAssistente();
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        if(bd.getAssistentes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        this.AssistenteAtual = this.AssistenteAtual - 1;
        
        //Usado para mostrar os dados do Assistente para o usuário
        //se ao clicar no botão anterior e o Assistente atual valer -1 que é uma posição fora do Array
        //para não ocorrer erro, deve entrar nesse if
        if(this.AssistenteAtual < 0){
            this.AssistenteAtual = 0;
            vizualizarAssistente(this.AssistenteAtual);
            return;
        }
        
        vizualizarAssistente(this.AssistenteAtual);
        
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmdproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdproximoActionPerformed
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        if(bd.getAssistentes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        
        this.AssistenteAtual = this.AssistenteAtual + 1;
        
        //Usado para mostrar os dados do Assistente para o usuário
        //se ao clicar no botão proximo e o Assistente atual exceder o valor do array criado
        //para não ocorrer erro, deve entrar nesse if
        if(this.AssistenteAtual > bd.retornaIndiceUltimoCadastroAssistente()){
           vizualizarAssistente(bd.retornaIndiceUltimoCadastroAssistente()); 
           this.AssistenteAtual = bd.retornaIndiceUltimoCadastroAssistente();
           return;
        }
        
        vizualizarAssistente(this.AssistenteAtual);
    }//GEN-LAST:event_cmdproximoActionPerformed

    private void cmdalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdalterarActionPerformed
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(false);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(false);
        alterarAssistente = true;
    }//GEN-LAST:event_cmdalterarActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        den.excluir(AssistenteAtual, bd);
        JOptionPane.showMessageDialog(rootPane, "Assistente excluido com sucesso");
    }//GEN-LAST:event_cmddeletarActionPerformed

    private void cmdbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbuscarActionPerformed
        
        String codAssistente = JOptionPane.showInputDialog("Favor digitar o código do Assistente: ");
        
        if(codAssistente.equals("")){
            return;
        }
        
        boolean flag = bd.verificaSeAssistenteExiste(Integer.valueOf(codAssistente));
        
        if(!flag){
            JOptionPane.showMessageDialog(rootPane, "Assistente não encontrado");
            return;
        }

        AssistenteAtual = bd.retornaPosAssistente(Integer.valueOf(codAssistente));
        vizualizarAssistente(AssistenteAtual);
    }//GEN-LAST:event_cmdbuscarActionPerformed

    //mostra os dados do Assistente no formulario
    private void vizualizarAssistente(int indice){
        
        txtid.setText(Integer.toString(bd.getAssistentes().get(indice).getId()));
        txtnome.setText(bd.getAssistentes().get(indice).getNome());
        txtendereco.setText(bd.getAssistentes().get(indice).getEndereco());
        txtcidade.setText(bd.getAssistentes().get(indice).getCidade());
        txtbairro.setText(bd.getAssistentes().get(indice).getBairro());
        txtrg.setText(bd.getAssistentes().get(indice).getRg());
        txtcpf.setText(bd.getAssistentes().get(indice).getCpf());
        txtemail.setText(bd.getAssistentes().get(indice).getEmail());
        txttelfixo.setText(Integer.toString(bd.getAssistentes().get(indice).getTelFixo()));
        txttelcel.setText(Integer.toString(bd.getAssistentes().get(indice).getTelCel()));
        txtsalario.setText(Double.toString(bd.getAssistentes().get(indice).getSalario()));
        jdadatapagamento.setDate(bd.getAssistentes().get(indice).getDataPagamento());
        txtsenha.setText(bd.getAssistentes().get(indice).getSenha());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcargo;
    private javax.swing.JButton cmdadicionar;
    private javax.swing.JButton cmdalterar;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdbuscar;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdprimeiro;
    private javax.swing.JButton cmdproximo;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdadatacontratacao;
    private com.toedter.calendar.JDateChooser jdadatapagamento;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelcel;
    private javax.swing.JTextField txttelfixo;
    // End of variables declaration//GEN-END:variables
}
