/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Assistente;
import Classes.Dentista;
import Classes.Fornecedor;
import Classes.Paciente;
import Classes.Secretaria;
import DBdados.Dados;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rails
 */
public class frmLogin extends javax.swing.JFrame {

   private Dentista den;
   private Dados bd;
   private Paciente pAuxiliar;
   private Assistente aAuxiliar;
   private Secretaria sAuxiliar;
   private Fornecedor fAuxiliar;

    public void atualizarDados(Dados bd, Dentista auxiliar, Paciente pAuxiliar, Assistente aAuxiliar, Secretaria sAuxiliar, Fornecedor fAuxiliar){
        this.bd = bd;
        this.den = auxiliar;
        this.pAuxiliar = pAuxiliar;
        this.aAuxiliar = aAuxiliar;
        this.sAuxiliar = sAuxiliar;
        this.fAuxiliar = fAuxiliar;
    }
    
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdentrar = new javax.swing.JButton();
        cmdsair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdentrar.setText("Entrar");
        cmdentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdentrarActionPerformed(evt);
            }
        });

        cmdsair.setText("Sair");
        cmdsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsairActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha");

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cmdentrar)
                        .addGap(103, 103, 103)
                        .addComponent(cmdsair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnome)
                            .addComponent(txtsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdentrar)
                    .addComponent(cmdsair))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmdsairActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void cmdentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdentrarActionPerformed
        // TODO add your handling code here:
        
        if (den.validaDentista(txtnome.getText(), new String (txtsenha.getPassword()), bd)){
            //abrir menu
            JOptionPane.showMessageDialog(rootPane, "Usuário e senha corretas");
        } else if(aAuxiliar.validaAssistente(txtnome.getText(), new String (txtsenha.getPassword()), bd)){
            JOptionPane.showMessageDialog(rootPane, "Usuário e senha corretas");
        } else if(sAuxiliar.validaSecretaria(txtnome.getText(), new String (txtsenha.getPassword()), bd)){
             JOptionPane.showMessageDialog(rootPane, "Usuário e senha corretas");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário e senha incorretas");    
            return;
        }

        //Após realizar o login será aberto o menu do sistema
        frmMenu frmmenu = new frmMenu();
        this.setVisible(false);//fecha a tela de login e deixa apenas a de menu aberta
        frmmenu.atualizarDados(bd, den, pAuxiliar, aAuxiliar, sAuxiliar, fAuxiliar);
        //String usuario = txtusuario.getText();
        //clsdados.setUsuarioLogado(usuario);
        frmmenu.setExtendedState(JFrame.MAXIMIZED_BOTH);//aumenta a tela para ajustar a janela
        frmmenu.setVisible(true);
 
    }//GEN-LAST:event_cmdentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdentrar;
    private javax.swing.JButton cmdsair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
