/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Material;
import java.util.ArrayList;

/**
 *
 * @author rails
 */
public class frmMaterial extends javax.swing.JFrame {

    /**
     * Creates new form frmProcedimento
     */
    
    //private int contador = 0;
    private ArrayList<Material> mat = new ArrayList();
    private boolean cancelar = false;
    private frmFornecedor ffornecedor = null;
    
    public void enviarFormularioFornecedor(frmFornecedor frmF){
        this.ffornecedor = frmF;
    }
    
    public frmMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbmaterial = new javax.swing.JComboBox<>();
        txtvalormaterial = new javax.swing.JTextField();
        cmdsalvar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtqtdmaterial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Material");

        jLabel1.setText("Tipo de Material:");

        jLabel2.setText("Valor do material:");

        cmbmaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar material", "adesivos", "cimento", "gel clareador", "resina", "brackets", "luva", "mascara", "algodão", "gaze", " " }));

        cmdsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/script_save.png"))); // NOI18N
        cmdsalvar.setToolTipText("salvar");
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        cmdcancelar.setToolTipText("cancelar");
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Qtd:");

        txtqtdmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdmaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqtdmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalormaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtqtdmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtvalormaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdsalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdcancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        String material = "";

        if (cmbmaterial.getSelectedIndex() == 1) {
            material = "adesivos";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 2) {
            material = "cimento";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 3) {
            material = "gel clareador";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 4) {
            material = "resina";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 5) {
            material = "brackets";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 6) {
            material = "luva";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 7) {
            material = "mascara";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

        if (cmbmaterial.getSelectedIndex() == 8) {
            material = "algodão";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }
        if (cmbmaterial.getSelectedIndex() == 9) {
            material = "gaze";
            Material m = new Material(material, Integer.parseInt(txtqtdmaterial.getText()), Float.parseFloat(txtvalormaterial.getText()));
            mat.add(m);

        }

    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        //System.out.println("Nome procedimento: " + pro.get(3).getNomeProcedimento());
        ffornecedor.enviarDadosFornecedor(mat);
        this.dispose();
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void txtqtdmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdmaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdmaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmaterial;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtqtdmaterial;
    private javax.swing.JTextField txtvalormaterial;
    // End of variables declaration//GEN-END:variables


}
