/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Assistente;
import Classes.Dentista;
import Classes.Fornecedor;
import Classes.Paciente;
import Classes.Secretaria;
import DBdados.Dados;
import javax.swing.JOptionPane;

/**
 *
 * @author rails
 */
public class frmMenu extends javax.swing.JFrame {

    private Dados bd;
    private Dentista den;
    private Paciente pAuxiliar;
    private Assistente aAuxiliar;
    private Secretaria sAuxiliar;
    private Fornecedor fAuxiliar;
    
    void atualizarDados(Dados bd, Dentista den, Paciente pAuxiliar, Assistente aAuxiliar, Secretaria sAuxiliar, Fornecedor fAuxiliar) {
        this.bd = bd;
        this.den = den;
        this.pAuxiliar = pAuxiliar;
        this.aAuxiliar = aAuxiliar;
        this.sAuxiliar = sAuxiliar;
        this.fAuxiliar = fAuxiliar;
    }
    
    
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deskpainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mncadastros = new javax.swing.JMenu();
        mncadastrosdentista = new javax.swing.JMenuItem();
        mncadastrofornecedor = new javax.swing.JMenuItem();
        mncadastrosassistente = new javax.swing.JMenuItem();
        mncadastrossecretaria = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mncadastrosair = new javax.swing.JMenuItem();
        mnmateriais = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnprocedimentos = new javax.swing.JMenu();
        mnprocedimentosprocedimentosmarcados = new javax.swing.JMenuItem();
        mnpagamentosfuncinarioss = new javax.swing.JMenu();
        mnpagamentosdentistas = new javax.swing.JMenuItem();
        mnpagamentosassistentes = new javax.swing.JMenuItem();
        mnpagamentossecretarias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Odontologico");

        javax.swing.GroupLayout DeskpainelLayout = new javax.swing.GroupLayout(Deskpainel);
        Deskpainel.setLayout(DeskpainelLayout);
        DeskpainelLayout.setHorizontalGroup(
            DeskpainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        DeskpainelLayout.setVerticalGroup(
            DeskpainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("Sistema Odontológico");

        mncadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Arquivo.png"))); // NOI18N
        mncadastros.setText("Cadastros");

        mncadastrosdentista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mncadastrosdentista.setText("Dentista");
        mncadastrosdentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncadastrosdentistaActionPerformed(evt);
            }
        });
        mncadastros.add(mncadastrosdentista);

        mncadastrofornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mncadastrofornecedor.setText("Fornecedor");
        mncadastrofornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncadastrofornecedorActionPerformed(evt);
            }
        });
        mncadastros.add(mncadastrofornecedor);

        mncadastrosassistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mncadastrosassistente.setText("Assistente");
        mncadastrosassistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncadastrosassistenteActionPerformed(evt);
            }
        });
        mncadastros.add(mncadastrosassistente);

        mncadastrossecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mncadastrossecretaria.setText("Secretaria");
        mncadastrossecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncadastrossecretariaActionPerformed(evt);
            }
        });
        mncadastros.add(mncadastrossecretaria);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        jMenuItem5.setText("Paciente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mncadastros.add(jMenuItem5);
        mncadastros.add(jSeparator1);

        mncadastrosair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        mncadastrosair.setText("Sair");
        mncadastrosair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncadastrosairActionPerformed(evt);
            }
        });
        mncadastros.add(mncadastrosair);

        jMenuBar1.add(mncadastros);

        mnmateriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produtos.png"))); // NOI18N
        mnmateriais.setText("Materiais");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pagamentos.png"))); // NOI18N
        jMenuItem7.setText("Materiais comprados");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnmateriais.add(jMenuItem7);

        jMenuBar1.add(mnmateriais);

        mnprocedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        mnprocedimentos.setText("Procedimentos");

        mnprocedimentosprocedimentosmarcados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white_paste.png"))); // NOI18N
        mnprocedimentosprocedimentosmarcados.setText("Procedimentos Marcados");
        mnprocedimentosprocedimentosmarcados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnprocedimentosprocedimentosmarcadosActionPerformed(evt);
            }
        });
        mnprocedimentos.add(mnprocedimentosprocedimentosmarcados);

        jMenuBar1.add(mnprocedimentos);

        mnpagamentosfuncinarioss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pagamentos.png"))); // NOI18N
        mnpagamentosfuncinarioss.setText("Pagamentos");

        mnpagamentosdentistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mnpagamentosdentistas.setText("Dentistas");
        mnpagamentosdentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpagamentosdentistasActionPerformed(evt);
            }
        });
        mnpagamentosfuncinarioss.add(mnpagamentosdentistas);

        mnpagamentosassistentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mnpagamentosassistentes.setText("Assistentes");
        mnpagamentosassistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpagamentosassistentesActionPerformed(evt);
            }
        });
        mnpagamentosfuncinarioss.add(mnpagamentosassistentes);

        mnpagamentossecretarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        mnpagamentossecretarias.setText("Secretarias");
        mnpagamentossecretarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpagamentossecretariasActionPerformed(evt);
            }
        });
        mnpagamentosfuncinarioss.add(mnpagamentossecretarias);

        jMenuBar1.add(mnpagamentosfuncinarioss);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mncadastrosdentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncadastrosdentistaActionPerformed
        frmDentista fdentista = new frmDentista();
        fdentista.atualizarDados(bd, den, pAuxiliar);
        Deskpainel.add(fdentista);
        fdentista.show();
    }//GEN-LAST:event_mncadastrosdentistaActionPerformed

    private void mnpagamentosdentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpagamentosdentistasActionPerformed
        frmContasAPagar fcontas = new frmContasAPagar();
        fcontas.atualizarDados(bd, den);
        Deskpainel.add(fcontas);
        fcontas.show();
    }//GEN-LAST:event_mnpagamentosdentistasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmPaciente fpaciente = new frmPaciente();
        fpaciente.enviarFormularioPaciente(fpaciente);
        fpaciente.atualizarDados(bd, den, pAuxiliar);
        Deskpainel.add(fpaciente);
        fpaciente.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnprocedimentosprocedimentosmarcadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnprocedimentosprocedimentosmarcadosActionPerformed
        frmProcedimentosMarcados fprocedimento = new frmProcedimentosMarcados();
        fprocedimento.atualizarDados(bd, den, pAuxiliar);
        Deskpainel.add(fprocedimento);
        fprocedimento.show();
    }//GEN-LAST:event_mnprocedimentosprocedimentosmarcadosActionPerformed

    private void mncadastrosassistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncadastrosassistenteActionPerformed
        frmAssistente fassistente = new frmAssistente();
        fassistente.atualizarDados(bd, den, pAuxiliar, aAuxiliar);
        Deskpainel.add(fassistente);
        fassistente.show();
    }//GEN-LAST:event_mncadastrosassistenteActionPerformed

    private void mnpagamentosassistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpagamentosassistentesActionPerformed
        frmContasAPagarAssistente fcontas = new frmContasAPagarAssistente();
        fcontas.atualizarDados(bd, aAuxiliar);
        Deskpainel.add(fcontas);
        fcontas.show();
    }//GEN-LAST:event_mnpagamentosassistentesActionPerformed

    private void mncadastrossecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncadastrossecretariaActionPerformed
        frmSecretaria fsecretaria = new frmSecretaria();
        fsecretaria.atualizarDados(bd, den, pAuxiliar, sAuxiliar);
        Deskpainel.add(fsecretaria);
        fsecretaria.show();
    }//GEN-LAST:event_mncadastrossecretariaActionPerformed

    private void mnpagamentossecretariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpagamentossecretariasActionPerformed
        frmContasAPagarSecretaria fsecretaria = new frmContasAPagarSecretaria();
        fsecretaria.atualizarDados(bd, sAuxiliar);
        Deskpainel.add(fsecretaria);
        fsecretaria.show();
    }//GEN-LAST:event_mnpagamentossecretariasActionPerformed

    private void mncadastrofornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncadastrofornecedorActionPerformed
        frmFornecedor ffornecedor = new frmFornecedor();
        ffornecedor.enviarFormularioFornecedor(ffornecedor);
        ffornecedor.atualizarDados(bd,fAuxiliar, pAuxiliar);
        Deskpainel.add(ffornecedor);
        ffornecedor.show();
    }//GEN-LAST:event_mncadastrofornecedorActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frmMateriaisComprados fmaterial = new frmMateriaisComprados();
        fmaterial.atualizarDados(bd, den, pAuxiliar);
        Deskpainel.add(fmaterial);
        fmaterial.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mncadastrosairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncadastrosairActionPerformed
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_mncadastrosairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Deskpainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mncadastrofornecedor;
    private javax.swing.JMenu mncadastros;
    private javax.swing.JMenuItem mncadastrosair;
    private javax.swing.JMenuItem mncadastrosassistente;
    private javax.swing.JMenuItem mncadastrosdentista;
    private javax.swing.JMenuItem mncadastrossecretaria;
    private javax.swing.JMenu mnmateriais;
    private javax.swing.JMenuItem mnpagamentosassistentes;
    private javax.swing.JMenuItem mnpagamentosdentistas;
    private javax.swing.JMenu mnpagamentosfuncinarioss;
    private javax.swing.JMenuItem mnpagamentossecretarias;
    private javax.swing.JMenu mnprocedimentos;
    private javax.swing.JMenuItem mnprocedimentosprocedimentosmarcados;
    // End of variables declaration//GEN-END:variables

  
}
