/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Dentista;
import Classes.Paciente;
import Classes.Procedimento;
import DBdados.Dados;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rails
 */
public class frmPaciente extends javax.swing.JInternalFrame {

    //private Dentista den = new Dentista(2, "railson", "a", "Can", "Par", "1515", "1212", "Dentista", new Date(), "a@a", 1515, 2020, "1212");
    
    private Dados bd;
    private Paciente pa;
    private int pacienteAtual = 0;
    private boolean alterarPaciente = false;
    private String nomeProcedimento = "";
    private String valorProcedimento = "";
    private ArrayList<Procedimento> pro = new ArrayList(); 
    private frmPaciente frmP = null;
    private Dentista den;
    private Paciente pAuxiliar;

            
        
    public void atualizarDados(Dados bd, Dentista den, Paciente pAuxiliar){
        this.bd = bd;
        this.den = den;
        this.pAuxiliar = pAuxiliar;
    }
    
    public void enviarDadosProcedimento(ArrayList<Procedimento> x){
        pro = x;
    }
    
    public void enviarFormularioPaciente(frmPaciente p){
        this.frmP = p;
    }
    
   
    public frmPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtrg = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txttelfixo = new javax.swing.JTextField();
        txttelcel = new javax.swing.JTextField();
        jdadataconsulta = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtuf = new javax.swing.JTextField();
        cmdprocedimentocadastrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmdadicionar = new javax.swing.JButton();
        cmdalterar = new javax.swing.JButton();
        cmddeletar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdbuscar = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdprimeiro = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdproximo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Paciente");

        jLabel1.setText("Identificador:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereco:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Rg:");

        jLabel7.setText("Cpf:");

        jLabel9.setText("Data da consulta:");

        jLabel11.setText("TelFixo:");

        jLabel12.setText("TelCel:");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrgActionPerformed(evt);
            }
        });

        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });

        jLabel8.setText("UF:");

        txtuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtufActionPerformed(evt);
            }
        });

        cmdprocedimentocadastrar.setText("Cadastrar");
        cmdprocedimentocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprocedimentocadastrarActionPerformed(evt);
            }
        });

        jLabel13.setText("Procedimento:");

        cmdadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        cmdadicionar.setToolTipText("adicionar");
        cmdadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdadicionarActionPerformed(evt);
            }
        });

        cmdalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        cmdalterar.setToolTipText("editar");
        cmdalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdalterarActionPerformed(evt);
            }
        });

        cmddeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        cmddeletar.setToolTipText("excluir");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        cmdcancelar.setToolTipText("cancelar");
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        cmdbuscar.setToolTipText("pesquisar");
        cmdbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbuscarActionPerformed(evt);
            }
        });

        cmdsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/script_save.png"))); // NOI18N
        cmdsalvar.setToolTipText("salvar");
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Proximo.png"))); // NOI18N
        cmdanterior.setToolTipText("anterior");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Primeiro.png"))); // NOI18N
        cmdprimeiro.setToolTipText("primeiro");
        cmdprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeiroActionPerformed(evt);
            }
        });

        cmdultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ultimo.png"))); // NOI18N
        cmdultimo.setToolTipText("ultimo");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Anterior.png"))); // NOI18N
        cmdproximo.setToolTipText("proximo");
        cmdproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdproximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtid))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtnome))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                        .addComponent(txtrg)
                                        .addComponent(txtbairro)
                                        .addComponent(txtcidade)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addComponent(jdadataconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cmdprocedimentocadastrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelcel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txttelfixo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(cmdadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jdadataconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttelfixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txttelcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdprocedimentocadastrar)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdadicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdalterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmddeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cmdsalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdcancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdanterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdproximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdultimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrgActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

   
    
    private void txtufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtufActionPerformed

    private void cmdprocedimentocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprocedimentocadastrarActionPerformed
        frmProcedimento frmprocedimento = new frmProcedimento();
        frmprocedimento.enviarFormularioPaciente(this.frmP);
        //this.setVisible(false);//fecha a tela de login e deixa apenas a de menu aberta
        //frprocedimento.atualizarDados(bd, den);
        //String usuario = txtusuario.getText();
        //clsdados.setUsuarioLogado(usuario);
        //frmprocedimento.setExtendedState(JFrame.M);//aumenta a tela para ajustar a janela
        frmprocedimento.setVisible(true);
    }//GEN-LAST:event_cmdprocedimentocadastrarActionPerformed

    private void cmdadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdadicionarActionPerformed

        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdadicionar.setEnabled(false);
        cmdalterar.setEnabled(false);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(false);

        txtid.setEnabled(true);
        txtnome.setEnabled(true);
        txtendereco.setEnabled(true);
        txtcidade.setEnabled(true);
        txtbairro.setEnabled(true);
        txtuf.setEnabled(true);
        txtrg.setEnabled(true);
        txtcpf.setEnabled(true);
        jdadataconsulta.setDate(null);
        txttelfixo.setEnabled(true);
        txttelcel.setEnabled(true);


        txtid.setText("");
        txtnome.setText("");
        jdadataconsulta.setDate(null);
        txtcidade.setText("");
        txtuf.setText("");
        txtendereco.setText("");
        txtbairro.setText("");
        txtrg.setText("");
        txtcpf.setText("");
        txttelfixo.setText("");
        txttelcel.setText("");
      

        //novo = true;
        txtid.requestFocusInWindow();
        
    }//GEN-LAST:event_cmdadicionarActionPerformed

    private void cmdalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdalterarActionPerformed
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(false);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(false);
        
        txtid.setEnabled(true);
        txtnome.setEnabled(true);
        txtendereco.setEnabled(true);
        txtcidade.setEnabled(true);
        txtbairro.setEnabled(true);
        txtuf.setEnabled(true);
        txtrg.setEnabled(true);
        txtcpf.setEnabled(true);
        jdadataconsulta.setDate(null);
        txttelfixo.setEnabled(true);
        txttelcel.setEnabled(true);

        //novo = true;
        txtnome.requestFocusInWindow();
        
        alterarPaciente = true; 
    }//GEN-LAST:event_cmdalterarActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        String msg =  pAuxiliar.excluir(pacienteAtual, bd);
       
        JOptionPane.showMessageDialog(rootPane, msg);
    }//GEN-LAST:event_cmddeletarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed

        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(false);
        cmdbuscar.setEnabled(true);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void cmdbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbuscarActionPerformed

        
        String codpaciente= JOptionPane.showInputDialog("Favor digitar o código do paciente: ");

        if(codpaciente.equals("")){
            return;
        }

        boolean flag = bd.verificaSePacienteExiste(Integer.valueOf(codpaciente));

        if(!flag){
            JOptionPane.showMessageDialog(rootPane, "paciente não encontrado");
            return;
        }

        pacienteAtual = bd.retornaPosPaciente(Integer.valueOf(codpaciente));
        vizualizarPacientes(pacienteAtual);
        
    }//GEN-LAST:event_cmdbuscarActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        //validação dos campos digitados pelo usuário
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o id para realizar o cadastro");
            txtid.requestFocusInWindow();//posicionar o cursor na barra
            return;
        }

        if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o nome para realizar o cadastro");
            txtnome.requestFocusInWindow();
            return;
        }

        if(txtendereco.getText().equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o endereco para realizar o cadastro");
            txtendereco.requestFocusInWindow();
            return;
        }

        if(txtbairro.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o bairro para realizar o cadastro");
            txtbairro.requestFocusInWindow();
            return;
        }

        if(txtcidade.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar a cidade para realizar o cadastro");
            txtcidade.requestFocusInWindow();
            return;
        }

        if(txtuf.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar a uf para realizar o cadastro");
            txtuf.requestFocusInWindow();
            return;
        }

        if(txtrg.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o rg para realizar o cadastro");
            txtrg.requestFocusInWindow();
            return;
        }

        if(txtcpf.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor digitar o cpf para realizar o cadastro");
            txtcpf.requestFocusInWindow();
            return;
        }
        
        boolean dataOcupada = den.pesquisarSeDataOcupada(jdadataconsulta.getDate(), bd);

        if(dataOcupada){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar uma nova data consulta para realizar o cadastro");
            jdadataconsulta.requestFocusInWindow();
            return;
        }

        if(txttelfixo.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o telefone fixo para realizar o cadastro");
            txttelfixo.requestFocusInWindow();
            return;
        }

        if(txttelcel.equals("")){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar o telefone celular para realizar o cadastro");
            txttelcel.requestFocusInWindow();
            return;
        }
        
        if(pro.size() == 0){
            JOptionPane.showMessageDialog((rootPane), "Favor selecionar os campos do procedimento para realizar o cadastro");
            //txttelcel.requestFocusInWindow();
            return;
        }
        
        for(int i = 0; i < pro.size(); i++){
            System.out.println("Nome procedimento: " + pro.get(i).getNomeProcedimento());
            System.out.println("Valor procedimento: " + pro.get(i).getValorProcedimento());
            System.out.println("----------------------------------");
        }

        //Salvando paciente no banco de dados
        
        //bd.inserirDataDentista(jdadataconsulta.getDate());

        Paciente p = new Paciente(Integer.parseInt(txtid.getText()),
                                                    txtnome.getText(),
                                                    txtendereco.getText(),
                                                    txtbairro.getText(),
                                                    txtcidade.getText(),
                                                    txtuf.getText(),
                                                    txtrg.getText(),
                                                    txtcpf.getText(),
                                                    Integer.parseInt(txttelfixo.getText()),
                                                    Integer.parseInt(txttelcel.getText()),
                                                    jdadataconsulta.getDate(),
                                                    pro);

        boolean pacienteExiste = p.pesquisar(Integer.parseInt(txtid.getText()), bd);

        
        if(pacienteExiste && this.alterarPaciente){
            this.alterarPaciente = false;
            pAuxiliar.editar(pacienteAtual, p, bd);
            JOptionPane.showMessageDialog(rootPane, "Paciente editado com sucesso");
            return;
        }
        

        if(pacienteExiste){
            JOptionPane.showMessageDialog(rootPane, "Paciente já existe no sistema");
            return;
        } else {
            p.cadastrar(p, bd);
            JOptionPane.showMessageDialog(rootPane, "Paciente cadastratdo com sucesso");
            //return;
        }

        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdbuscar.setEnabled(true);

        txtid.setEnabled(false);
        txtnome.setEnabled(false);
        txtendereco.setEnabled(false);
        txtcidade.setEnabled(false);
        txtbairro.setEnabled(false);
        txtrg.setEnabled(false);
        txtcpf.setEnabled(false);
        txtuf.setEnabled(false);
        jdadataconsulta.setDate(null);
        txttelfixo.setEnabled(false);
        txttelcel.setEnabled(false);
    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed

        
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        
        if(bd.getPacientes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        
        this.pacienteAtual = this.pacienteAtual - 1;
        
        

        //Usado para mostrar os dados do dentista para o usuário
        //se ao clicar no botão anterior e o dentista atual valer -1 que é uma posição fora do Array
        //para não ocorrer erro, deve entrar nesse if
        if(this.pacienteAtual < 0){
            this.pacienteAtual = 0;
            vizualizarPacientes(this.pacienteAtual);
            return;
        }

        vizualizarPacientes(this.pacienteAtual);

    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmdprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeiroActionPerformed

        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        if(bd.getPacientes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        
        vizualizarPacientes(0);
        this.pacienteAtual = 0;

    }//GEN-LAST:event_cmdprimeiroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        if(bd.getPacientes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }
        vizualizarPacientes(bd.retornaIndiceUltimoCadastroPaciente());
        this.pacienteAtual = bd.retornaIndiceUltimoCadastroPaciente();
        
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdproximoActionPerformed

        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdadicionar.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdbuscar.setEnabled(true);
        this.pacienteAtual = this.pacienteAtual + 1;
        
        if(bd.getPacientes().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Não existe dados no banco! ");
            return;
        }

        //Usado para mostrar os dados do paciente para o usuário
        //se ao clicar no botão proximo e o paciente atual exceder o valor do array criado
        //para não ocorrer erro, deve entrar nesse if
        if(this.pacienteAtual > bd.retornaIndiceUltimoCadastroPaciente()){
            vizualizarPacientes(bd.retornaIndiceUltimoCadastroPaciente());
            this.pacienteAtual = bd.retornaIndiceUltimoCadastro();
            return;
        }

        vizualizarPacientes(this.pacienteAtual);

    }//GEN-LAST:event_cmdproximoActionPerformed
    
    //mostra os dados do dentista no formulario
    private void vizualizarPacientes(int indice){
        txtid.setText(Integer.toString(bd.getPacientes().get(indice).getId()));
        txtnome.setText(bd.getPacientes().get(indice).getNome());
        txtendereco.setText(bd.getPacientes().get(indice).getEndereco());
        txtcidade.setText(bd.getPacientes().get(indice).getCidade());
        txtbairro.setText(bd.getPacientes().get(indice).getBairro());
        txtrg.setText(bd.getPacientes().get(indice).getRg());
        txtcpf.setText(bd.getPacientes().get(indice).getCpf());
        txtuf.setText(bd.getPacientes().get(indice).getUf());
        jdadataconsulta.setDate(bd.getPacientes().get(indice).getDataConsulta());
        txttelfixo.setText(Integer.toString(bd.getPacientes().get(indice).getTelFixo()));
        txttelcel.setText(Integer.toString(bd.getPacientes().get(indice).getTelCel()));
   
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdadicionar;
    private javax.swing.JButton cmdalterar;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdbuscar;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdprimeiro;
    private javax.swing.JButton cmdprocedimentocadastrar;
    private javax.swing.JButton cmdproximo;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdadataconsulta;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txttelcel;
    private javax.swing.JTextField txttelfixo;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
}
